FROM ubuntu:18.04
WORKDIR /go/src/app

# tz-data default
ENV DEBIAN_FRONTEND=noninteractive

# Update and upgrade repo
RUN apt-get update -y -q && apt-get upgrade -y -q 

# Install tools needed
RUN apt-get install -y -q curl \
	build-essential \
	ca-certificates \
	git \
	wget \
	gnupg2

# golang
RUN apt-get install -y -q golang-go

# python
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       apt-utils \
       python-setuptools \
       python-pip \
       software-properties-common \
       rsyslog systemd systemd-cron sudo \
	   python-dev \
    && rm -Rf /var/lib/apt/lists/* \
    && rm -Rf /usr/share/doc && rm -Rf /usr/share/man \
    && apt-get clean

# init Golang
ENV GOPATH $HOME/go
ENV PATH $PATH:$HOME/go/bin:/usr/local/go/bin
RUN mkdir -p $GOPATH/bin
RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

# packages
RUN pip install wheel
